### ISSUE TITLE
我们需要全球化的文档，让更多人的开发者接触到她

### ISSUE THREAD

**Issue by newbe36524** [dotnetcore/Natasha.Docs#1]
- [x] 我们需要一个单独的仓库，用于存储文档的仓库，以便更容易的实现文档的发布和测试
- [x] 我们需要确定发布了域名 natasha.dotnet-china.org
- [x] 我们需要集成 Crowdin.com 以便实现文档翻译为多国语
- [x] 我们需要项目的图标
- [x] 我们需要项目的 Slogan

#44

**Comment by NMSAzulX** [comment]
目前项目图标:  https://avatars2.githubusercontent.com/u/51699821 , 设计理念 :  Natahsha 既可以创造, 又可以利用类库. 类似于创生万物, 归于我用.  该图标也是 Night Moon Studio 组织的图标, 该组织为基于 Natasha 创造的类库.  该设计参照太极图样, 绘画比较粗糙, 可以替换或改善.

**Comment by ryuujo1573** [comment]
前来支持（也许我可以帮忙翻译，英语/日语）

**Comment by newbe36524** [comment]
初版已经上线。后续将会添加若干操作手册，更多的朋友们参与其中
